export const productsData = [
    {
      id: 1,
      imageUrl: 'https://content1.rozetka.com.ua/goods/images/big/398085596.jpg',
      name: 'Мобільний телефон Samsung Galaxy S24 Ultra 12GB/1TB Titanium Black',
      price: 79899,
      isRunningOut: false,
      description: 'Екран (6.8", Dynamic AMOLED 2X, 3120x1440) / Qualcomm Snapdragon 8 Gen 3 for Galaxy (3.4 ГГц + 3.15 ГГц + 2.96 ГГц + 2.27 ГГц) / основна квадрокамера: 200 Мп + 50 Мп + 12 Мп + 10 Мп, фронтальна 12 Мп / RAM 12 ГБ / 512 ГБ вбудованої памяті / 3G / LTE / 5G / GPS / підтримка 2х SIM-карток (Nano-SIM) / Android 14 / 5000 мА * год',
      specifications: {
        screen: '6.8" Dynamic AMOLED',
        processor: 'Exynos 2100',
        camera: '108 MP + 10 MP + 10 MP + 12 MP',
        battery: '5000 mAh',
        os: 'Android 12',
      },
      photos: {
        photo1: 'https://content2.rozetka.com.ua/rich_content/rich_content_files/original/398356478.webp',
        photo2: 'https://content1.rozetka.com.ua/rich_content/rich_content_files/original/398356489.webp',
        photo3: 'https://content1.rozetka.com.ua/rich_content/rich_content_files/original/398356493.webp',
        photo4: 'https://content2.rozetka.com.ua/rich_content/rich_content_files/original/398356497.webp',
        photo5: 'https://content1.rozetka.com.ua/rich_content/rich_content_files/original/398356502.webp',
        photo6: 'https://content.rozetka.com.ua/rich_content/rich_content_files/original/398356516.webp',
      },
    },
    {
      id: 2,
      imageUrl: 'https://content.rozetka.com.ua/goods/images/big/406667556.jpg',
      name: 'Ноутбук Acer Predator Helios Neo 16 PHN16-71-92X4',
      price: 29999,
      isRunningOut: true,
      description: 'Опис ноутбука Acer Predator Helios...',
      specifications: {
        screen: '16" IPS',
        processor: 'Intel Core i9',
        ram: '32 GB',
        storage: '1 TB SSD',
        os: 'Windows 11',
      },
      photos: {
        photo1: 'https://content.rozetka.com.ua/rich_content/rich_content_files/original/422794480.webp',
        photo2: 'https://content.rozetka.com.ua/rich_content/rich_content_files/original/422795540.webp',
        photo3: 'https://content2.rozetka.com.ua/rich_content/rich_content_files/original/422794607.webp',
        photo4: 'https://content1.rozetka.com.ua/rich_content/rich_content_files/original/422794657.webp',
        photo5: 'https://content.rozetka.com.ua/rich_content/rich_content_files/original/422794688.webp',
        photo6: 'https://content1.rozetka.com.ua/rich_content/rich_content_files/original/422794851.webp',
      },
    },
    {
      id: 3,
      imageUrl: 'https://content2.rozetka.com.ua/goods/images/big/430252027.jpg',
      name: 'ТБ TCL 98C955',
      price: 345999,
      isRunningOut: false,
      description: 'Тип: QLED-телевізори / Комунікації: WiFi, Bluetooth, DLNA / Оснащення: Вбудований медіаплеєр, Smart TV / TV-тюнер: аналоговий, DVB-T2, DVB-S2, DVB-C / Вихід в інтернет: Ethernet (RJ-45) / Wi-Fi / Екран: 98" (3840x2160) 4K Ultra HD / Тюнер: DVB-C, DVB-S2, DVB-T2 + аналоговий / Потужність звуку: 80 Вт / Операційна система: Google TV / Розєми: Цифровий оптичний аудіовиход, Компонентний вхід, Ethernet, USB, HDMI / Місце знаходження: Домашній кінотеатр / Клас енергоспоживання: F / Оптимальна відстань до глядача: 655 см / Аудіодекодери: Dolby Atmos',
      specifications: {
        screen: '98" QLED',
        resolution: '8K',
        hdr: 'Dolby Vision',
        smartTV: 'Android TV',
      },
      photos: {
        photo1: '1',
        photo2: '1',
        photo3: '1',
        photo4: '1',
        photo5: '1',
        photo6: '1',
      },
    },
    {
      id: 4,
      imageUrl: 'https://content2.rozetka.com.ua/goods/images/big/430252027.jpg',
      name: 'ТБ TCL 98C955',
      price: 345999,
      isRunningOut: false,
      description: 'Опис ТБ TCL 98C955...',
      specifications: {
        screen: '98" QLED',
        resolution: '8K',
        hdr: 'Dolby Vision',
        smartTV: 'Android TV',
      },
      photos: {
        photo1: '1',
        photo2: '1',
        photo3: '1',
        photo4: '1',
        photo5: '1',
        photo6: '1',
      },
    },
];